# Site settings
title: Shankar Karki
subtitle: Energy Quant
description: Making Energy Markets Computable. I build optimization and forecasting algorithms for electricity markets.
baseurl: ""
url: "https://shankarkarki.github.io"  # ✅ FIXED: Your actual domain

# Author
author:
  name: Shankar Karki
  email: shankar.karki660@gmail.com
  github: shankarkarki
  linkedin: shankar-karki

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag  # ✅ ADDED: For better SEO

# Math rendering (✅ ADDED for your MLF equations)
kramdown:
  math_engine: mathjax

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Shankar Karki"

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
